version: "3.8"

x-shared-settings: &shared-settings
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./chromadb:/opt/chromadb
    - ./include/data:/opt/data/
  networks:
    - airflow

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  airflow-webserver:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow_webserver
    <<: *shared-settings
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${AIRFLOW_WEBSERVER_PORT}:${AIRFLOW_WEBSERVER_PORT}"
    entrypoint: ["${AIRFLOW_HOME}/entrypoint.sh", "webserver"]

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow_scheduler
    <<: *shared-settings
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["${AIRFLOW_HOME}/entrypoint.sh", "scheduler"]

  airflow-init:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow_init
    <<: *shared-settings
    env_file:
      - .env
    depends_on:
      - postgres
    command: ["airflow", "db", "init"]

  gradio:
    image: ${AIRFLOW_IMAGE}
    container_name: gradio-chatbot
    environment:
      - KEY=VALUE
    env_file:
      - .env
    ports:
      - "${GRADIO_WEB_PORT}:${GRADIO_WEB_PORT}"
    volumes:
      - ./chromadb:${persist_directory}
      - ./include/gradio:${GRADIO_HOME}
      - ./include/data:${INLINE_DATA_VOLUME}
    entrypoint: ["python3", "${GRADIO_HOME}/app.py"]
    networks:
      - airflow

networks:
  airflow:
    driver: bridge